version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis-service
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build: .
    container_name: cardcost-api-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis-service
      - SPRING_REDIS_PORT=6379
    networks:
      - app-network
    depends_on:
      - redis

networks:
  app-network:
    driver: bridge
